language : node_js
node_js :
 - 10
install:
 - yarn install
script:
  - docker build -t $DOCKER_USER/zzc-wechat-helper:latest .
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_USER/zzc-wechat-helper:latest
  - docker tag $DOCKER_USER/zzc-wechat-helper:latest $DOCKER_USER/zzc-wechat-helper:`git describe --abbrev=0 --tags`
  - docker push $DOCKER_USER/zzc-wechat-helper:`git describe --abbrev=0 --tags`